### PR TITLE
Improve version handling to be on par with imcsdk

### PR DESCRIPTION
**Pull request by vesposito**
imcsdk's version handling code has been improved over time to better support internal/engineering versions, but this has not been synced to ucsmsdk.
This pull request fixes that.

### CODE REVIEW

**Comment by techyragu** [comment]
@vesposito - could you please add few test cases for all the different version support you added as a part of this PR. Thanks

**Comment by vesposito** [comment]
@techyragu Sure, but can you please give me some ideas of what you're looking for? Do you want me to build a unit test for this? You would need to connect to various devices with internal engineering releases for this

**Comment by techyragu** [comment]
@vesposito 
https://github.com/CiscoUcs/imcsdk/blob/master/tests/unit_tests/common/test_imcversion.py

**Comment by techyragu** [comment]
@vesposito Also, please raise your PR against master.

**Comment by vesposito** [comment]
OK thanks. Will do!

**Comment by vesposito** [comment]
Replaced by https://github.com/CiscoUcs/ucsmsdk/pull/208

**Pull request closed without merging**
