### PR TITLE
Reducing cyclomatic complexity of ucssession

### PR DESCRIPTION
**Pull request by vvb**
(1) Reducing cyclomatic complexity of ucssession - `__create_uri` method
(2) adding testcases for it
(3) adhering to 80 char limit

### CODE REVIEW

**Comment by ragupta-git** [comment]
Now UcsSession will not have secure and port attributes.

**Comment by vvb** [comment]
@ragupta-git I don't know why we were saving them? I do not see them getting used. Do you know?

**Comment by ragupta-git** [comment]
@vvb I am not using it as such. But thought of keeping all in handle. If I see handle object I will come to know which port and  if connection is secure or not. Even while freezing the handle these properties  will be available.

**Comment by vvb** [comment]
@ragupta-git `self.__uri` has all that info.. let us add it when we really use it.

**Pull request merged**
